### ISSUE TITLE
Potential ape-etherscan bug

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher-contracts#203]
While deploying TACoApp contract in Sepolia, I got this:
```
(...)
SUCCESS: Contract 'TransparentUpgradeableProxy' deployed to: 0xE9Eb81F72cDBE9fE82f61EA527e8a3A39f5B023a

Wrapping TACoApplication into TransparentUpgradeableProxy (as type TACoApplication) at 0xE9Eb81F72cDBE9fE82f61EA527e8a3A39f5B023a.
INFO: `ape-cache` database has not been initialized
Traceback (most recent call last):
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/ape/_cli.py", line 36, in invoke
    return super().invoke(ctx)
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/ape_run/_cli.py", line 74, in invoke
    return super().invoke(ctx)
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/ape/cli/commands.py", line 18, in invoke
    super().invoke(ctx)
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/ape_run/_cli.py", line 146, in call
    main_ns["main"]()  # Execute the script
  File "/Users/david/dev/nu/nucypher-contracts/scripts/dashboard/deploy_root.py", line 24, in main
    deployer.finalize(deployments=deployments)
  File "/Users/david/dev/nu/nucypher-contracts/deployment/params.py", line 621, in finalize
    registry_from_ape_deployments(
  File "/Users/david/dev/nu/nucypher-contracts/deployment/registry.py", line 199, in registry_from_ape_deployments
    entries = _get_entries(contract_instances=deployments, registry_names=registry_names)
  File "/Users/david/dev/nu/nucypher-contracts/deployment/registry.py", line 81, in _get_entries
    entry = _get_entry(contract_instance=contract_instance, registry_names=registry_names)
  File "/Users/david/dev/nu/nucypher-contracts/deployment/registry.py", line 62, in _get_entry
    receipt = contract_instance.receipt
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/ape/contracts/base.py", line 868, in receipt
    receipt = self.chain_manager.contracts.get_creation_receipt(self.address)
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/ape/managers/chain.py", line 1435, in get_creation_receipt
    return next(creation_receipts)
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/ape_etherscan/query.py", line 100, in get_contract_creation_receipt
    creation_data = client.get_creation_data()
  File "/Users/david/.local/share/virtualenvs/nucypher-contracts-QkvTNaSR/lib/python3.10/site-packages/ape_etherscan/client.py", line 352, in get_creation_data
    assert isinstance(result.value, list)
AssertionError
((nucypher-contracts) ) david@Davids-MacBook-Pro-2 nucypher-contracts % 
```

My setting:
```
eth-ape==0.6.20
ape-etherscan==0.6.10
ape-infura==0.6.4
ape-polygon==0.6.6
ape-solidity==0.6.9
```

**Comment by derekpierre** [comment]
May be solved given our updates to ape dependencies via #237 ...

We have successfully done a deployment of Coordinator contract with the updated dependencies.

**Comment by cygnusv** [comment]
> We have successfully done a deployment of Coordinator contract with the updated dependencies.

Yes but without automatic etherscan verification, that hasn't been tried in a while. In any case, I'd say let's close this and re-open if we see it in the future.
